FW.i = FW.d.createElement('iframe'); 
var s=FW.i.style; 
FW.i.src='http://'+FW.env+'/iform?u='+FW.u+'&url='+encodeURIComponent(FW.l.href);
FW.i.id='fauxwerd';
FW.i.width='600px';
FW.i.height='150px';
s.position = 'fixed'; 
s.left=(FW.d.documentElement.clientWidth/2) -300+'px'; 
s.top = '0'; s.border = '0';
s.zIndex='9999999';
FW.i.setAttribute('frameBorder','0px');
FW.i.setAttribute('allowTransparency',true);
FW.b.appendChild(FW.i); 
fauxwerdBeGone(1);